# version: "3.8"

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql8-container
#     restart: always
#     env_file:
#       - .env
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./mysql_config:/docker-entrypoint-initdb.d  # init.sql 실행
#     ports:
#       - "3306:3306"

#   fastapi:
#     build: .
#     container_name: fastapi-log-api
#     restart: always
#     env_file:
#       - .env
#     depends_on:
#       - mysql
#     ports:
#       - "8000:8000"

#   nginx:
#     image: nginx:latest
#     container_name: fastapi-nginx
#     restart: always
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - fastapi
#     ports:
#       - "80:80"

# volumes:
#   mysql_data:


version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-container
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_config:/docker-entrypoint-initdb.d  # init.sql 실행
    ports:
      - "3306:3306"
    networks:
      - app-network

  fastapi:
    build: .
    container_name: fastapi-log-api
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: fastapi-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
